import { z } from "zod";

export const personDetailsFetchSchema = z
    .object({
        adult: z.boolean(),
        also_known_as: z.array(z.string()),
        biography: z.string(),
        birthday: z.string(),
        deathday: z.null(),
        gender: z.number(),
        homepage: z.null(),
        id: z.number(),
        imdb_id: z.string(),
        known_for_department: z.string(),
        name: z.string(),
        place_of_birth: z.string(),
        popularity: z.number(),
        profile_path: z.string(),
    })
    .transform(
        ({
            also_known_as,
            place_of_birth,
            imdb_id,
            known_for_department,
            profile_path,
            ...rest
        }) => ({
            alsoKnownAs: also_known_as,
            placeOfBirth: place_of_birth,
            imdbId: imdb_id,
            knownForDepartment: known_for_department,
            picture: profile_path,
            ...rest,
        })
    );

export type IPersonDetailsFetch = z.infer<typeof personDetailsFetchSchema>;

export const personCreditsSchema = z.object({
    cast: z.array(
        z.union([
            z.object({
                adult: z.boolean(),
                backdrop_path: z.string().nullable(),
                genre_ids: z.array(z.number()),
                id: z.number(),
                original_language: z.string(),
                original_title: z.string(),
                overview: z.string(),
                popularity: z.number(),
                poster_path: z.string().nullable(),
                release_date: z.string(),
                title: z.string(),
                video: z.boolean(),
                vote_average: z.number(),
                vote_count: z.number(),
                character: z.string(),
                credit_id: z.string(),
                order: z.number(),
            }),
            z.object({
                adult: z.boolean(),
                backdrop_path: z.null(),
                genre_ids: z.array(z.number()),
                id: z.number(),
                original_language: z.string(),
                original_title: z.string(),
                overview: z.string(),
                popularity: z.number(),
                poster_path: z.string().nullable(),
                release_date: z.string(),
                title: z.string(),
                video: z.boolean(),
                vote_average: z.number(),
                vote_count: z.number(),
                character: z.string(),
                credit_id: z.string(),
                order: z.number(),
            }),
            z.object({
                adult: z.boolean(),
                backdrop_path: z.null(),
                genre_ids: z.array(z.number()),
                id: z.number(),
                original_language: z.string(),
                original_title: z.string(),
                overview: z.string(),
                popularity: z.number(),
                poster_path: z.null(),
                release_date: z.string(),
                title: z.string(),
                video: z.boolean(),
                vote_average: z.number(),
                vote_count: z.number(),
                character: z.string(),
                credit_id: z.string(),
                order: z.number(),
            }),
            z.object({
                adult: z.boolean(),
                backdrop_path: z.null(),
                genre_ids: z.array(z.unknown()),
                id: z.number(),
                original_language: z.string(),
                original_title: z.string(),
                overview: z.string(),
                popularity: z.number(),
                poster_path: z.string().nullable(),
                release_date: z.string(),
                title: z.string(),
                video: z.boolean(),
                vote_average: z.number(),
                vote_count: z.number(),
                character: z.string(),
                credit_id: z.string(),
                order: z.number(),
            }),
            z.object({
                adult: z.boolean(),
                backdrop_path: z.string().nullable(),
                genre_ids: z.array(z.number()),
                id: z.number(),
                original_language: z.string(),
                original_title: z.string(),
                overview: z.string(),
                popularity: z.number(),
                poster_path: z.null(),
                release_date: z.string(),
                title: z.string(),
                video: z.boolean(),
                vote_average: z.number(),
                vote_count: z.number(),
                character: z.string(),
                credit_id: z.string(),
                order: z.number(),
            }),
        ])
    ),
    crew: z.array(
        z.union([
            z.object({
                adult: z.boolean(),
                backdrop_path: z.null(),
                genre_ids: z.array(z.number()),
                id: z.number(),
                original_language: z.string(),
                original_title: z.string(),
                overview: z.string(),
                popularity: z.number(),
                poster_path: z.string().nullable(),
                release_date: z.string(),
                title: z.string(),
                video: z.boolean(),
                vote_average: z.number(),
                vote_count: z.number(),
                credit_id: z.string(),
                department: z.string(),
                job: z.string(),
            }),
            z.object({
                adult: z.boolean(),
                backdrop_path: z.string().nullable(),
                genre_ids: z.array(z.number()),
                id: z.number(),
                original_language: z.string(),
                original_title: z.string(),
                overview: z.string(),
                popularity: z.number(),
                poster_path: z.string().nullable(),
                release_date: z.string(),
                title: z.string(),
                video: z.boolean(),
                vote_average: z.number(),
                vote_count: z.number(),
                credit_id: z.string(),
                department: z.string(),
                job: z.string(),
            }),
        ])
    ),
    id: z.number(),
});

export type IPersonCreditsFetch = z.infer<typeof personCreditsSchema>;
