import Head from "next/head";
import Layout from "@/components/common/Layout/Layout";
import Link from "next/link";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="ml-[100px] flex flex-col gap-6 lg:gap-8">
                    <dl className="w-full gap-6 md:columns-2 lg:gap-10 xl:columns-3 2xl:columns-4">
                        <Link
                            href={{
                                pathname: "/movies/all/",
                                query: {
                                    decade: "2020",
                                    genre: "Action",
                                },
                            }}
                        >
                            <h1>hello</h1>
                        </Link>
                    </dl>
                </div>
            </Layout>
        </>
    );
}

// function AuthShowcase() {
//     const { data: sessionData } = useSession();

//     const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//         undefined, // no input
//         { enabled: sessionData?.user !== undefined }
//     );

//     return (
//         <div className="flex flex-col items-center justify-center gap-4">
//             <p className="text-center text-2xl text-white">
//                 {sessionData && (
//                     <span>Logged in as {sessionData.user?.name}</span>
//                 )}
//                 {secretMessage && <span> - {secretMessage}</span>}
//             </p>
//             <button
//                 className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//                 onClick={
//                     sessionData ? () => void signOut() : () => void signIn()
//                 }
//             >
//                 {sessionData ? "Sign out" : "Sign in"}
//             </button>
//         </div>
//     );
// }
